### ISSUE TITLE
peekView colors are not consistently applied

### ISSUE THREAD

**Issue by dimgrav** [artvandelay440/VSCodePopTheme#6]
Using:
- Pop!_OS 18.04
- VS Code v1.40.1

I have installed the theme using the built-in **Extensions** feature in VS Code.

I'm using the **Pop Dark** variation and I noticed that the `peekView` colors are not properly applied, which is not the case for the Light/Color variations:

![Screenshot from 2019-11-14 12-39-04](https://user-images.githubusercontent.com/24510850/68850181-2d409380-06dc-11ea-8ddd-f331c72d501f.png)

By setting the `peekViewTitle.background` property in global `settings.json`, I am able to apply another color:

![Screenshot from 2019-11-14 12-39-32](https://user-images.githubusercontent.com/24510850/68850249-59f4ab00-06dc-11ea-84e5-f066f69d1abc.png)

However, trying to override `peekView.border` has no effect.

**Comment by ArtisanByteCrafter** [comment]
Nice find! I'll look into this and get it updated soon

**Comment by ArtisanByteCrafter** [comment]
I should have this fixed now. I've got one other thing i want to look at then i can get an update published.

![Capture](https://user-images.githubusercontent.com/2523522/68887552-d092a800-06de-11ea-9d82-fcbf9644ecd7.PNG)

**Comment by ArtisanByteCrafter** [comment]
@dimgrav The update has been pushed - version 1.0.2 should now fix this, please update and let me know!

**Comment by dimgrav** [comment]
Thanks for the swift replay and action!

The `peekView` looks as per your screenshot now! However, the git diff border color is still not properly overridden (it's value is still `#11667d` as shown in the second screenshot I posted previously).

I went through the [docs](https://code.visualstudio.com/api/references/theme-color) myself to find if it's another component that's responsible for rendering the git diffs, but it's doesn't look like it.

**Comment by dimgrav** [comment]
Thanks for the swift reply and action!

The `peekView` looks as per your screenshot now! However, the git diff border color is still not properly overridden (its value is still `#11667d` as shown in the second screenshot I posted previously).

I went through the [docs](https://code.visualstudio.com/api/references/theme-color) myself to find if it's another component that's responsible for rendering the git diffs, but it doesn't look like it.

**Comment by ArtisanByteCrafter** [comment]
That's so odd. I'm my testing (screenshot I posted) it applies the peek border correctly. as a test, could you download the Insiders vscode and see if the peek border applies correctly there? Might be a sneaky setting somewhere in your vscode settings

**Comment by dimgrav** [comment]
Perhaps I wasn't clear enough.

File peek in `peekView`:
![Screenshot from 2019-11-15 16-36-38](https://user-images.githubusercontent.com/24510850/68951189-3dcd3880-07c6-11ea-9cb9-e16580f811c7.png)

Git diff in `peekView`:
![Screenshot from 2019-11-15 16-36-55](https://user-images.githubusercontent.com/24510850/68951210-47ef3700-07c6-11ea-8b5d-7336e3cff875.png)

I'll do what you proposed and provide you with some feedback.

**Comment by ArtisanByteCrafter** [comment]
Ah gotcha, that might be different settings, I'll take a look too.
